### ISSUE TITLE
Gem files in load path can interfere with project files

### ISSUE THREAD

**Issue by amuino** [DanielVartanov/ruby-geometry#14]
When using ruby geometry in our project, the following entry is added to the ruby load path:

`"/Users/amuino/.rvm/gems/ruby-2.1.6@cabify/gems/ruby-geometry-0.0.5/lib"`

The issue is that the folder contains several files that shadow our own (or viceversa, depending on how we setup the load path) when using `require`. One such files is `point.rb` (we have our own `point.rb` in the project).

Just to clarify, this is not a problem with class names (we use `Point`, the gem provides `Geometry::Point`) but with loading of files.

A [common practice](http://guides.rubygems.org/patterns/#consistent-naming) with gems is to package the files in a subfolder (except for the main file).

This would translate into having:

```
lib/geometry.rb
lib/geometry/point.rb
lib/geometry/...
...
```

I can work on a PR for the changes, but first wanted to confirm that it is ok to follow this path.

**Comment by DanielVartanov** [comment]
Hi @amuino 

Huge thanks for bringing this up. Current dirs/files structure is definitely a mistake (because it was initiated many many years ago), I've been procrastinating to solve this problem for too long. Yes, please go for a PR, I will be happy to accept it.

Thanks again!
Daniel.

**Comment by amuino** [comment]
Done in #15, I will close this issue now.
